/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.hello.proto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface ClientHello {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"ClientHello\",\"namespace\":\"avro.hello.proto\",\"types\":[],\"messages\":{\"state\":{\"request\":[{\"name\":\"username\",\"type\":\"string\"}],\"response\":\"string\"},\"change\":{\"request\":[{\"name\":\"username\",\"type\":\"string\"}],\"response\":\"string\"}}}");
  java.lang.CharSequence state(java.lang.CharSequence username) throws org.apache.avro.AvroRemoteException;
  java.lang.CharSequence change(java.lang.CharSequence username) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends ClientHello {
    public static final org.apache.avro.Protocol PROTOCOL = avro.hello.proto.ClientHello.PROTOCOL;
    void state(java.lang.CharSequence username, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void change(java.lang.CharSequence username, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
  }
}