/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.hello.proto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Hello {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Hello\",\"namespace\":\"avro.hello.proto\",\"types\":[],\"messages\":{\"enter\":{\"request\":[{\"name\":\"ip\",\"type\":\"string\"}],\"response\":\"string\"},\"leave\":{\"request\":[{\"name\":\"username\",\"type\":\"string\"}],\"response\":\"string\"}}}");
  java.lang.CharSequence enter(java.lang.CharSequence ip) throws org.apache.avro.AvroRemoteException;
  java.lang.CharSequence leave(java.lang.CharSequence username) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends Hello {
    public static final org.apache.avro.Protocol PROTOCOL = avro.hello.proto.Hello.PROTOCOL;
    void enter(java.lang.CharSequence ip, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void leave(java.lang.CharSequence username, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
  }
}