/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sourcefiles;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface FridgeProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"FridgeProtocol\",\"namespace\":\"sourcefiles\",\"types\":[],\"messages\":{\"getInventory\":{\"request\":[],\"response\":{\"type\":\"array\",\"items\":\"string\"}},\"addItem\":{\"request\":[{\"name\":\"item\",\"type\":\"string\"}],\"response\":\"string\"},\"removeItem\":{\"request\":[{\"name\":\"item\",\"type\":\"string\"}],\"response\":\"string\"}}}");
  java.util.List<java.lang.CharSequence> getInventory() throws org.apache.avro.AvroRemoteException;
  java.lang.CharSequence addItem(java.lang.CharSequence item) throws org.apache.avro.AvroRemoteException;
  java.lang.CharSequence removeItem(java.lang.CharSequence item) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends FridgeProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = sourcefiles.FridgeProtocol.PROTOCOL;
    void getInventory(org.apache.avro.ipc.Callback<java.util.List<java.lang.CharSequence>> callback) throws java.io.IOException;
    void addItem(java.lang.CharSequence item, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void removeItem(java.lang.CharSequence item, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
  }
}