/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sourcefiles;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface lightprotocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"lightprotocol\",\"namespace\":\"sourcefiles\",\"types\":[],\"messages\":{\"changestate\":{\"request\":[],\"response\":\"boolean\"}}}");
  boolean changestate() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends lightprotocol {
    public static final org.apache.avro.Protocol PROTOCOL = sourcefiles.lightprotocol.PROTOCOL;
    void changestate(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
  }
}