/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sourcefiles;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface TSProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"TSProtocol\",\"namespace\":\"sourcefiles\",\"types\":[],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends TSProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = sourcefiles.TSProtocol.PROTOCOL;
  }
}