/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sourcefiles;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface UserProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"UserProtocol\",\"namespace\":\"sourcefiles\",\"types\":[{\"type\":\"record\",\"name\":\"TemperatureRecord\",\"fields\":[{\"name\":\"time\",\"type\":\"string\"},{\"name\":\"temperature\",\"type\":\"double\"}]},{\"type\":\"record\",\"name\":\"TemperatureAggregate\",\"fields\":[{\"name\":\"counter\",\"type\":\"int\"},{\"name\":\"record\",\"type\":\"TemperatureRecord\"}]}],\"messages\":{\"notifyOfEmptyFridge\":{\"request\":[{\"name\":\"fridgeName\",\"type\":\"string\"}],\"response\":\"string\"},\"notifyUsers\":{\"request\":[{\"name\":\"userName\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"}],\"response\":\"null\"},\"enter\":{\"request\":[{\"name\":\"userName\",\"type\":\"string\"},{\"name\":\"ip\",\"type\":\"string\"}],\"response\":\"null\"},\"leave\":{\"request\":[{\"name\":\"userName\",\"type\":\"string\"}],\"response\":\"null\"},\"enterHouse\":{\"request\":[{\"name\":\"userName\",\"type\":\"string\"}],\"response\":\"null\"},\"leaveHouse\":{\"request\":[{\"name\":\"userName\",\"type\":\"string\"}],\"response\":\"null\"},\"updateTemperature\":{\"request\":[{\"name\":\"TemperatureAggregate\",\"type\":\"TemperatureAggregate\"}],\"response\":\"null\"}}}");
  java.lang.CharSequence notifyOfEmptyFridge(java.lang.CharSequence fridgeName) throws org.apache.avro.AvroRemoteException;
  java.lang.Void notifyUsers(java.lang.CharSequence userName, java.lang.CharSequence state) throws org.apache.avro.AvroRemoteException;
  java.lang.Void enter(java.lang.CharSequence userName, java.lang.CharSequence ip) throws org.apache.avro.AvroRemoteException;
  java.lang.Void leave(java.lang.CharSequence userName) throws org.apache.avro.AvroRemoteException;
  java.lang.Void enterHouse(java.lang.CharSequence userName) throws org.apache.avro.AvroRemoteException;
  java.lang.Void leaveHouse(java.lang.CharSequence userName) throws org.apache.avro.AvroRemoteException;
  java.lang.Void updateTemperature(sourcefiles.TemperatureAggregate TemperatureAggregate) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends UserProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = sourcefiles.UserProtocol.PROTOCOL;
    void notifyOfEmptyFridge(java.lang.CharSequence fridgeName, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void notifyUsers(java.lang.CharSequence userName, java.lang.CharSequence state, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void enter(java.lang.CharSequence userName, java.lang.CharSequence ip, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void leave(java.lang.CharSequence userName, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void enterHouse(java.lang.CharSequence userName, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void leaveHouse(java.lang.CharSequence userName, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void updateTemperature(sourcefiles.TemperatureAggregate TemperatureAggregate, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}